version: 2
jobs:
  build:
    machine: true
    environment:
      - PHOENIX_ECR: 564677439943.dkr.ecr.ap-northeast-1.amazonaws.com/h3poteto/pleroma/phoenix
      - NGINX_ECR: 564677439943.dkr.ecr.ap-northeast-1.amazonaws.com/h3poteto/pleroma/nginx
    steps:
      - checkout
      - run:
          name: phoenix docker build
          command: |
            docker build -t $PHOENIX_ECR:$CIRCLE_SHA1 -f dockerfiles/phoenix/Dockerfile .
      - run:
          name: phoenix docker push
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker push $PHOENIX_ECR:$CIRCLE_SHA1
      - run:
          name: nginx docker build
          command: |
            cd dockerfiles/nginx
            docker build -t $NGINX_ECR:latest .
      - run:
          name: nginx docker push
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker push $NGINX_ECR:latest
